name: Build, Create JAR

on:
  push:
    branches:
      - main  # or replace with the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Javadocs
        run: mvn javadoc:javadoc --file pom.xml

      - name: Upload JAR and Javadocs
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: |
            target/*.jar
            target/site/apidocs/
